[[language]]
name = "nix"
language-servers = [ "nixd" ]
formatter = { command = "nixpkgs-fmt" }

[language-server.nixd]
command = "nixd"

[[language]]
name = "toml"
formatter = { command = "taplo", args = [ "fmt", "-" ] }

